# Generated by Django 6.0.3 on 2026-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('requester', 'Requester'), ('agent', 'Agent'), ('manager', 'Manager')], default='requester', max_length=20),
        ),
    ]
