# Generated by Django 6.0.3 on 2026-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('blacklisted', 'Blacklisted'), ('deactivated', 'Deactivated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
