# Generated by Django 6.0.3 on 2026-03-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signup Secret',
            },
        ),
    ]
