# Generated by Django 6.0.3 on 2026-03-13 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0001_initial'),
        ('teams', '0002_team_members_department_team_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='teams.department'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='servicedesk.category'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
