# Generated by Django 6.0.3 on 2026-03-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0002_alter_category_options_category_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('hours', models.JSONField(default=list, help_text='Business hours per day')),
                ('holidays', models.JSONField(default=list, help_text='Holiday dates as ISO strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='servicedesk.ticketresponse'),
        ),
        migrations.AddField(
            model_name='ticketresponse',
            name='is_from_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketresponse',
            name='message_type',
            field=models.CharField(choices=[('public_reply', 'Public Reply'), ('internal_note', 'Internal Note')], default='public_reply', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('pending', 'Pending'), ('on_hold', 'On Hold'), ('solved', 'Solved'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.JSONField(default=dict, help_text='Policy matching conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicedesk.businessschedule')),
            ],
            options={
                'verbose_name_plural': 'SLA Policies',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TicketSLAInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('target_minutes', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_pause_minutes', models.IntegerField(default=0)),
                ('active_business_minutes', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('fulfilled', 'Fulfilled'), ('breached', 'Breached')], default='active', max_length=20)),
                ('last_event_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicedesk.slapolicy')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_instances', to='servicedesk.serviceticket')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('old_state', models.CharField(blank=True, max_length=20)),
                ('new_state', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_audit_logs', to='servicedesk.serviceticket')),
                ('sla_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicedesk.ticketslainstance')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SLATarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('first_reply_time', 'First Reply Time'), ('next_reply_time', 'Next Reply Time'), ('pausable_update_time', 'Pausable Update Time'), ('requester_wait_time', 'Requester Wait Time'), ('agent_work_time', 'Agent Work Time'), ('total_resolution_time', 'Total Resolution Time')], max_length=50)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], max_length=20)),
                ('target_minutes', models.IntegerField(help_text='Target in business minutes')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='servicedesk.slapolicy')),
            ],
            options={
                'unique_together': {('policy', 'metric', 'priority')},
            },
        ),
    ]
