# Generated by Django 6.0.3 on 2026-03-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0003_businessschedule_attachment_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapolicy',
            name='category',
            field=models.ForeignKey(blank=True, help_text='When set, this policy applies to tickets in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='servicedesk.category'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default fallback policy when no specific match'),
        ),
    ]
