# Generated by Django 6.0.3 on 2026-03-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0005_serviceticket_reference_id'),
        ('teams', '0003_department_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='slapolicy',
            name='category',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='teams.team'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='team',
            field=models.ForeignKey(blank=True, help_text='When set, this policy applies to tickets in this team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='teams.team'),
        ),
    ]
