# Generated by Django 6.0.3 on 2026-03-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0006_remove_serviceticket_category_and_more'),
        ('teams', '0003_department_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapolicy',
            name='department',
            field=models.ForeignKey(blank=True, help_text='When set, this policy applies to tickets in this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='teams.department'),
        ),
    ]
