# Generated by Django 6.0.3 on 2026-03-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0007_add_department_to_slapolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapolicy',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='System factory default policy from org_config.py'),
        ),
    ]
